### ISSUE TITLE
Key separation in uk layout

### ISSUE THREAD

**Issue by stenox** [timdream/gaia-keyboard-demo#13]
Looking at uk layout of keyboard I see the problem with separation of some keys.

Here is screenshot:

![qjfd2px](https://cloud.githubusercontent.com/assets/7978799/13637358/9fa56fd2-e60f-11e5-9299-ffd7514295bc.png)

I suspect, that the problem might be somewhere in ratio values for two bottom rows in uk.js
https://github.com/mozilla-b2g/gaia/blob/8633318d298bedcf0a6d628277fee2c29b6dc450/apps/keyboard/js/layouts/uk.js#L31

        { value: 'ю' }, { value: '⌫', **ratio: 1.5**, keyCode: KeyEvent.DOM_VK_BACK_SPACE }
      ], [
        { value: '&nbsp', **ratio: 10**, keyCode: KeyboardEvent.DOM_VK_SPACE },

**Comment by timdream** [comment]
> I suspect, that the problem might be somewhere in ratio values for two bottom rows in uk.js
> https://github.com/mozilla-b2g/gaia/blob/8633318d298bedcf0a6d628277fee2c29b6dc450/apps/keyboard/js/layouts/uk.js#L31

Yes! I realized that some time later after asking you to file an issue here. This should be filed on Bugzilla under Gaia:Keyboard -- [bug 1255257](https://bugzilla.mozilla.org/show_bug.cgi?id=1255257).
